# Generated by Django 6.0.7 on 2026-09-06 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(default='AI Soil Fertility Model Prediction', max_length=100)),
                ('predicted_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('soil_condition', models.CharField(blank=True, max_length=255)),
                ('possible_problem', models.TextField(blank=True)),
                ('crop_suitability', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('organic_methods', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(default='AI Water Quality Model Classification', max_length=100)),
                ('predicted_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('water_status', models.CharField(blank=True, max_length=255)),
                ('suitability', models.TextField(blank=True)),
                ('observations', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
