// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTarf7jAm0xLzBx-O1sg67Fs9xk9ia8sY',
    appId: '1:1009954673436:web:00379cfd266754712260d9',
    messagingSenderId: '1009954673436',
    projectId: 'smartcrop-3a999',
    authDomain: 'smartcrop-3a999.firebaseapp.com',
    storageBucket: 'smartcrop-3a999.firebasestorage.app',
    measurementId: 'G-5M4V4TBKMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgERRutjuXZbJIp8EglJyCKw4ZY9w0R48',
    appId: '1:1009954673436:android:62ff675f7fa6eb2a2260d9',
    messagingSenderId: '1009954673436',
    projectId: 'smartcrop-3a999',
    storageBucket: 'smartcrop-3a999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxgeCPsaKMsceGZ3wKCRuNWzx9yN4Y0i4',
    appId: '1:1009954673436:ios:8152bcf3472dc13a2260d9',
    messagingSenderId: '1009954673436',
    projectId: 'smartcrop-3a999',
    storageBucket: 'smartcrop-3a999.firebasestorage.app',
    iosBundleId: 'com.example.cropFarming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxgeCPsaKMsceGZ3wKCRuNWzx9yN4Y0i4',
    appId: '1:1009954673436:ios:8152bcf3472dc13a2260d9',
    messagingSenderId: '1009954673436',
    projectId: 'smartcrop-3a999',
    storageBucket: 'smartcrop-3a999.firebasestorage.app',
    iosBundleId: 'com.example.cropFarming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTarf7jAm0xLzBx-O1sg67Fs9xk9ia8sY',
    appId: '1:1009954673436:web:6621b0badfd0dba52260d9',
    messagingSenderId: '1009954673436',
    projectId: 'smartcrop-3a999',
    authDomain: 'smartcrop-3a999.firebaseapp.com',
    storageBucket: 'smartcrop-3a999.firebasestorage.app',
    measurementId: 'G-F4MNCRLLH9',
  );
}
