# Generated by Django 6.0.7 on 2026-08-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PumpThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture_min', models.FloatField(default=30.0, help_text='Soil moisture percentage below which irrigation should trigger (%)')),
                ('water_level_min', models.FloatField(default=20.0, help_text='Minimum tank water level percentage required to safely operate the pump (%)')),
                ('auto_control_enabled', models.BooleanField(default=True, help_text='Whether automatic pump decision is enabled')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pump Threshold Config',
                'verbose_name_plural': 'Pump Threshold Config',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField(help_text='Soil moisture percentage (0-100%)')),
                ('water_level', models.FloatField(help_text='Water level percentage (0-100%)')),
                ('temperature', models.FloatField(help_text='Ambient temperature in Celsius (°C)')),
                ('humidity', models.FloatField(help_text='Relative humidity percentage (0-100%)')),
                ('pump_status', models.BooleanField(default=False, help_text='Current pump state (True=ON, False=OFF)')),
                ('pump_mode', models.CharField(default='AUTO', help_text='Pump operation mode (AUTO/MANUAL)', max_length=20)),
                ('device_id', models.CharField(blank=True, default='ESP32_WOKWI_01', help_text='Device identifier', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
