# Generated by Django 6.0.7 on 2026-08-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpthresholdconfig',
            name='soil_moisture_optimal_max',
            field=models.FloatField(default=70.0, help_text='Soil moisture percentage above which soil is considered wet (%)'),
        ),
        migrations.AddField(
            model_name='pumpthresholdconfig',
            name='water_level_excess',
            field=models.FloatField(default=75.0, help_text='Field water availability percentage above which waterlogging risk occurs (%)'),
        ),
        migrations.AlterField(
            model_name='pumpthresholdconfig',
            name='water_level_min',
            field=models.FloatField(default=20.0, help_text='Minimum field water availability percentage required to safely operate the pump (%)'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='water_level',
            field=models.FloatField(help_text='Field water availability percentage (0-100%)'),
        ),
    ]
