# Generated by Django 6.0.7 on 2026-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/%Y/%m/%d/')),
                ('crop_name', models.CharField(blank=True, max_length=100)),
                ('predicted_disease', models.CharField(max_length=200)),
                ('confidence', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('treatment_advice', models.TextField(blank=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
