# Generated by Django 6.0.7 on 2026-08-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_key', models.CharField(help_text='Must match the AI model class name exactly, e.g. Tomato___Early_blight', max_length=200, unique=True)),
                ('crop_name', models.CharField(max_length=100)),
                ('disease_name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('symptoms', models.TextField(help_text='Visible symptoms on the plant')),
                ('description', models.TextField(help_text='Description of the disease and how it spreads')),
                ('organic_treatment', models.CharField(blank=True, max_length=300)),
                ('organic_dosage', models.CharField(blank=True, max_length=200)),
                ('organic_instructions', models.TextField(blank=True)),
                ('chemical_treatment', models.CharField(blank=True, max_length=300)),
                ('chemical_dosage', models.CharField(blank=True, max_length=200)),
                ('chemical_instructions', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('farming_tips', models.TextField(blank=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disease Information',
                'verbose_name_plural': 'Disease Information',
                'ordering': ['crop_name', 'disease_name'],
            },
        ),
        migrations.AddField(
            model_name='diseaseprediction',
            name='disease_key',
            field=models.CharField(blank=True, help_text='Raw AI class key for DB lookup', max_length=200),
        ),
    ]
