# Generated by Django 6.0.7 on 2026-08-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
