"""
Management command: seed_disease_info
Pre-populates DiseaseInfo table with data for all major PlantVillage classes.
Run: python manage.py seed_disease_info
"""
from django.core.management.base import BaseCommand
from disease.models import DiseaseInfo


DISEASE_DATA = [
    # ── Tomato ──────────────────────────────────────────────────────────────────
    {
        'disease_key': 'Tomato___Early_blight',
        'crop_name': 'Tomato',
        'disease_name': 'Early Blight',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Dark brown to black spots with concentric rings (target-board pattern) on older lower leaves. Yellow halo around spots. Leaves turn yellow and fall off. Stem lesions near soil level.',
        'description': 'Early blight is caused by the fungus Alternaria solani. It spreads through infected plant debris and water splash. Warm (24–29°C), humid conditions with frequent rain or dew promote rapid spread.',
        'organic_treatment': 'Copper-based fungicide (Copper Oxychloride)',
        'organic_dosage': '3 g per litre of water',
        'organic_instructions': 'Spray on leaves (both sides) every 7–10 days. Apply in early morning. Remove and destroy infected leaves before spraying. Avoid spraying in direct midday heat.',
        'chemical_treatment': 'Chlorothalonil or Mancozeb fungicide',
        'chemical_dosage': 'Chlorothalonil: 2 g/L water | Mancozeb: 2.5 g/L water',
        'chemical_instructions': 'Apply as a preventive spray every 7 days during humid weather. Do not apply within 7 days of harvest. Rotate between fungicide groups to avoid resistance.',
        'prevention': 'Practice crop rotation (3-year cycle). Remove infected plant debris. Ensure good air circulation by proper spacing. Avoid overhead watering. Use disease-resistant tomato varieties.',
        'farming_tips': 'Mulch around plants to prevent soil splash onto leaves. Stake or cage tomatoes to improve airflow. Water at the base of the plant in the morning.',
    },
    {
        'disease_key': 'Tomato___Late_blight',
        'crop_name': 'Tomato',
        'disease_name': 'Late Blight',
        'severity': 'Critical',
        'is_healthy': False,
        'symptoms': 'Water-soaked, greasy-looking dark green to brown patches on leaves. White fuzzy growth (fungal spores) on the underside of leaves in humid conditions. Brown lesions on stems and fruit rot.',
        'description': 'Late blight is caused by Phytophthora infestans — the same pathogen that caused the Irish Potato Famine. It spreads rapidly in cool (10–25°C), wet, and humid conditions. An entire crop can be destroyed within days if not controlled.',
        'organic_treatment': 'Copper Hydroxide (Kocide) or Bordeaux mixture',
        'organic_dosage': 'Copper Hydroxide: 3 g/L | Bordeaux mixture: 10 g/L',
        'organic_instructions': 'Begin spraying at first sign of disease. Spray every 5–7 days. Cover all leaf surfaces. Remove and burn infected plants immediately to prevent spread.',
        'chemical_treatment': 'Metalaxyl + Mancozeb (Ridomil Gold) or Cymoxanil',
        'chemical_dosage': 'Ridomil Gold: 2.5 g/L water | Cymoxanil: 2 g/L water',
        'chemical_instructions': 'Apply at first symptom appearance. Repeat every 7 days. Do not wait for disease to spread. Observe pre-harvest intervals strictly (14 days for most products).',
        'prevention': 'Plant resistant varieties. Avoid overhead irrigation. Space plants well for airflow. Do not compost infected plant material. Destroy crop debris after harvest.',
        'farming_tips': 'Scout plants twice a week during cool rainy seasons. If more than 10% of plants show symptoms, remove and burn them. Never carry infected plant material across the field.',
    },
    {
        'disease_key': 'Tomato___Bacterial_spot',
        'crop_name': 'Tomato',
        'disease_name': 'Bacterial Spot',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Small, water-soaked spots on leaves that turn dark brown with yellow halos. Spots on fruits appear as small, raised, scabby lesions. Severely infected leaves drop early.',
        'description': 'Caused by Xanthomonas bacteria. Spreads through rain splash, infected seeds, and contaminated tools. Warm, wet weather promotes rapid spread.',
        'organic_treatment': 'Copper bactericide (Copper Sulphate + Lime)',
        'organic_dosage': '3 g copper sulphate + 3 g lime per litre of water',
        'organic_instructions': 'Spray when disease first appears. Repeat every 7–10 days. Spray in early morning. Sanitize all tools with bleach solution.',
        'chemical_treatment': 'Copper Oxychloride + Streptomycin (if permitted locally)',
        'chemical_dosage': 'Copper Oxychloride: 3 g/L | Streptomycin: as per label',
        'chemical_instructions': 'Apply preventively during wet weather. Note: Streptomycin use regulations vary by country. Check local agricultural guidelines.',
        'prevention': 'Use certified disease-free seeds. Rotate crops. Avoid working in wet fields. Remove infected plants.',
        'farming_tips': 'Stake tomatoes well to improve air circulation. Avoid wetting leaves during irrigation.',
    },
    {
        'disease_key': 'Tomato___Leaf_Mold',
        'crop_name': 'Tomato',
        'disease_name': 'Leaf Mold',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Pale green or yellow spots on upper leaf surface. Olive-green to brown velvety mold growth on the underside. Leaves curl upward and dry out.',
        'description': 'Caused by Fulvia fulva fungus. Most common in greenhouses and humid environments. Spreads through airborne spores.',
        'organic_treatment': 'Neem oil or potassium bicarbonate spray',
        'organic_dosage': 'Neem oil: 5 mL/L water with mild soap | Potassium bicarbonate: 5 g/L',
        'organic_instructions': 'Spray both sides of leaves. Apply every 7 days. Improve ventilation in greenhouses.',
        'chemical_treatment': 'Chlorothalonil or Mancozeb',
        'chemical_dosage': '2 g/L water',
        'chemical_instructions': 'Apply preventively when weather is humid. Repeat every 7–10 days.',
        'prevention': 'Ensure good air circulation. Reduce humidity in greenhouses. Remove infected leaves. Avoid overhead watering.',
        'farming_tips': 'Open greenhouse vents in the morning to reduce humidity. Train plants on stakes for better airflow.',
    },
    {
        'disease_key': 'Tomato___Septoria_leaf_spot',
        'crop_name': 'Tomato',
        'disease_name': 'Septoria Leaf Spot',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Numerous small, circular spots (3–5 mm) with dark brown borders and tan/grey centers on lower leaves. Tiny black dots (pycnidia) visible inside spots. Leaves yellow and drop.',
        'description': 'Caused by Septoria lycopersici fungus. Spreads by rain splash. Warm, wet conditions accelerate disease. One of the most common tomato leaf diseases.',
        'organic_treatment': 'Copper-based fungicide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply at first sign of disease. Spray every 7–10 days. Remove heavily infected lower leaves.',
        'chemical_treatment': 'Mancozeb or Chlorothalonil',
        'chemical_dosage': '2–2.5 g/L water',
        'chemical_instructions': 'Apply preventively during rainy seasons. Rotate fungicide classes to avoid resistance.',
        'prevention': 'Remove and destroy infected leaves. Avoid overhead watering. Mulch soil to prevent splash. Rotate crops.',
        'farming_tips': 'Stake tomatoes to keep leaves off the ground. Prune lower leaves when they touch the soil.',
    },
    {
        'disease_key': 'Tomato___Spider_mites Two-spotted_spider_mite',
        'crop_name': 'Tomato',
        'disease_name': 'Spider Mites (Two-spotted)',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Tiny yellow or white speckling on upper leaf surface. Leaves look bronzed or silvery. Fine webbing under leaves. Leaves dry out and drop. Very small mites visible with magnifying glass.',
        'description': 'Two-spotted spider mites (Tetranychus urticae) are not insects — they are arachnids. They feed on plant sap. Hot, dry conditions promote rapid population explosions.',
        'organic_treatment': 'Neem oil spray or insecticidal soap',
        'organic_dosage': 'Neem oil: 5 mL/L | Insecticidal soap: 10 mL/L',
        'organic_instructions': 'Spray undersides of leaves thoroughly. Repeat every 5–7 days. Strong water spray can also knock mites off plants.',
        'chemical_treatment': 'Abamectin or Bifenazate miticide',
        'chemical_dosage': 'As per product label (usually 1–2 mL/L)',
        'chemical_instructions': 'Apply when mites first appear. Do not use general insecticides as they kill natural predators. Rotate miticide classes.',
        'prevention': 'Maintain adequate irrigation (mites thrive in dry conditions). Avoid excessive nitrogen fertilizer. Introduce predatory mites as biological control.',
        'farming_tips': 'Check underside of leaves regularly. Natural predators like predatory mites and lacewings help control spider mite populations.',
    },
    {
        'disease_key': 'Tomato___Target_Spot',
        'crop_name': 'Tomato',
        'disease_name': 'Target Spot',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Brown circular spots with concentric rings (like a target) on leaves, stems, and fruit. Spots have a yellow halo. Lower leaves affected first.',
        'description': 'Caused by Corynespora cassiicola fungus. Favored by warm, humid conditions. Can cause significant defoliation.',
        'organic_treatment': 'Copper oxychloride',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Spray preventively during warm humid seasons. Remove infected leaves.',
        'chemical_treatment': 'Azoxystrobin or Difenoconazole',
        'chemical_dosage': '1 mL/L water',
        'chemical_instructions': 'Apply at first symptom. Repeat every 10–14 days. Observe pre-harvest intervals.',
        'prevention': 'Avoid dense planting. Ensure good ventilation. Rotate crops. Remove plant debris after harvest.',
        'farming_tips': 'Prune suckers and lower leaves to improve air circulation in the crop canopy.',
    },
    {
        'disease_key': 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
        'crop_name': 'Tomato',
        'disease_name': 'Tomato Yellow Leaf Curl Virus',
        'severity': 'Critical',
        'is_healthy': False,
        'symptoms': 'Leaves curl upward and inward. Leaves turn yellow at margins. Plants are stunted. Flowers drop without fruit setting. Young leaves are small and distorted.',
        'description': 'A viral disease transmitted by the silverleaf whitefly (Bemisia tabaci). Once infected, there is no cure — focus on preventing spread by controlling the whitefly vector.',
        'organic_treatment': 'Yellow sticky traps + Neem oil spray to control whiteflies',
        'organic_dosage': 'Neem oil: 5 mL/L water',
        'organic_instructions': 'Place yellow sticky traps near plants. Spray neem oil weekly to reduce whitefly populations. Remove and destroy infected plants immediately.',
        'chemical_treatment': 'Imidacloprid or Thiamethoxam insecticide (for whitefly control)',
        'chemical_dosage': '0.5 mL/L water',
        'chemical_instructions': 'Apply as soil drench or foliar spray for whitefly control. Use reflective mulch to repel whiteflies. There is no cure for the virus itself.',
        'prevention': 'Plant resistant tomato varieties. Use insect-proof net houses for seedlings. Remove infected plants early. Control weed hosts of whiteflies.',
        'farming_tips': 'Never take infected plant cuttings. Wash hands and tools after handling infected plants. Reflective silver mulch significantly reduces whitefly landing.',
    },
    {
        'disease_key': 'Tomato___Tomato_mosaic_virus',
        'crop_name': 'Tomato',
        'disease_name': 'Tomato Mosaic Virus',
        'severity': 'High',
        'is_healthy': False,
        'symptoms': 'Mottled light and dark green pattern on leaves. Leaves may be distorted or fern-like. Fruits show yellow streaks. Plants may be stunted.',
        'description': 'Spread by mechanical contact (hands, tools, clothing) and seeds. Highly contagious — a single infected plant can spread the virus throughout the field. No cure exists once infected.',
        'organic_treatment': 'No chemical treatment. Remove infected plants.',
        'organic_dosage': 'N/A',
        'organic_instructions': 'Remove and destroy infected plants. Do not compost them. Wash hands with soap before and after working with plants. Dip tools in 10% bleach solution.',
        'chemical_treatment': 'No effective chemical treatment for the virus itself.',
        'chemical_dosage': 'N/A',
        'chemical_instructions': 'Focus on sanitation and prevention. Use virus-free seeds and resistant varieties.',
        'prevention': 'Use certified virus-free seeds. Control aphids and other vectors. Wash hands frequently. Do not use tobacco products near tomatoes (tobacco mosaic virus is related).',
        'farming_tips': 'Plant virus-resistant tomato varieties. Disinfect all tools after use. Remove infected plants as soon as symptoms are seen.',
    },
    {
        'disease_key': 'Tomato___healthy',
        'crop_name': 'Tomato',
        'disease_name': 'Healthy',
        'severity': 'Low',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Leaves are deep green and firm. Plant is growing vigorously.',
        'description': 'The crop appears healthy. Continue regular care and monitoring.',
        'organic_treatment': 'No treatment needed',
        'organic_dosage': 'N/A',
        'organic_instructions': 'Continue regular organic care practices.',
        'chemical_treatment': 'No treatment needed',
        'chemical_dosage': 'N/A',
        'chemical_instructions': 'Continue regular monitoring.',
        'prevention': 'Continue crop rotation, proper spacing, and regular scouting. Maintain adequate watering and nutrition.',
        'farming_tips': 'Scout your crop weekly for early signs of disease. Keep detailed records of spray applications. Maintain soil health with compost.',
    },

    # ── Potato ──────────────────────────────────────────────────────────────────
    {
        'disease_key': 'Potato___Early_blight',
        'crop_name': 'Potato',
        'disease_name': 'Early Blight',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Dark brown spots with concentric rings on lower, older leaves. Yellow halo around spots. Leaves turn yellow and wither. Lesions may appear on tubers as dark, sunken areas.',
        'description': 'Caused by Alternaria solani. Spreads through infected plant debris and water splash. Warm days (24–29°C) with heavy dew or rain promote disease. Stressed or nutrient-deficient plants are more susceptible.',
        'organic_treatment': 'Copper Oxychloride or Bordeaux mixture',
        'organic_dosage': 'Copper Oxychloride: 3 g/L | Bordeaux mixture: 10 g/L',
        'organic_instructions': 'Spray every 7–10 days from emergence. Cover all leaf surfaces. Remove and destroy infected leaves. Apply in early morning.',
        'chemical_treatment': 'Mancozeb or Chlorothalonil',
        'chemical_dosage': 'Mancozeb: 2.5 g/L | Chlorothalonil: 2 g/L',
        'chemical_instructions': 'Apply preventively before disease appears in humid conditions. Repeat every 7 days during rainy seasons.',
        'prevention': 'Rotate crops (do not grow potatoes in the same field for 3 years). Remove crop debris. Plant certified disease-free seed tubers. Maintain adequate fertility.',
        'farming_tips': 'Ensure adequate potassium fertilization as it improves disease resistance. Hill up potato plants to protect tubers from infection.',
    },
    {
        'disease_key': 'Potato___Late_blight',
        'crop_name': 'Potato',
        'disease_name': 'Late Blight',
        'severity': 'Critical',
        'is_healthy': False,
        'symptoms': 'Water-soaked pale green spots on leaf edges that enlarge rapidly into dark brown/black lesions. White cottony growth on leaf underside. Stems show dark brown rot. Infected tubers develop brown, firm internal rot.',
        'description': 'Caused by Phytophthora infestans. This is the most destructive potato disease worldwide. Spreads extremely fast under cool (10–20°C) and humid conditions. An entire crop can be lost in days without treatment.',
        'organic_treatment': 'Copper Hydroxide (Kocide) or Bordeaux mixture',
        'organic_dosage': 'Copper Hydroxide: 3 g/L | Bordeaux mixture: 10 g/L',
        'organic_instructions': 'Begin preventive spraying at first sign or when forecast indicates cool, wet weather. Spray every 5–7 days. Remove and burn infected haulm immediately.',
        'chemical_treatment': 'Metalaxyl-M + Mancozeb (Ridomil Gold MZ) or Cymoxanil + Mancozeb',
        'chemical_dosage': 'Ridomil Gold MZ: 2.5 g/L water',
        'chemical_instructions': 'Apply at first symptom. Repeat every 7 days. Desiccate haulm (kill tops) 2 weeks before harvest to reduce tuber infection.',
        'prevention': 'Plant certified disease-free seed potatoes. Use resistant varieties. Destroy cull potatoes and volunteer plants. Avoid overhead irrigation. Ensure good drainage.',
        'farming_tips': 'Monitor weather forecasts — if cool and rainy weather is expected, spray preventively even before symptoms appear. Contact your local extension office if disease spreads rapidly.',
    },
    {
        'disease_key': 'Potato___healthy',
        'crop_name': 'Potato',
        'disease_name': 'Healthy',
        'severity': 'Low',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Leaves are green and plants are growing normally.',
        'description': 'The potato crop appears healthy. Continue regular care.',
        'organic_treatment': 'No treatment needed',
        'organic_dosage': 'N/A',
        'organic_instructions': 'Continue regular care and monitoring.',
        'chemical_treatment': 'No treatment needed',
        'chemical_dosage': 'N/A',
        'chemical_instructions': 'Continue preventive fungicide program if disease pressure is high in your area.',
        'prevention': 'Use certified seed potatoes. Practice crop rotation. Control weeds. Maintain proper plant spacing.',
        'farming_tips': 'Hill potatoes when plants are 20–25 cm tall to prevent tuber greening and protect from blight.',
    },

    # ── Apple ───────────────────────────────────────────────────────────────────
    {
        'disease_key': 'Apple___Apple_scab',
        'crop_name': 'Apple',
        'disease_name': 'Apple Scab',
        'severity': 'High',
        'is_healthy': False,
        'symptoms': 'Olive-green to brown velvety spots on leaves. Spots on fruit appear as dark, scabby, cracked areas. Severely infected leaves drop early. Distorted fruit.',
        'description': 'Caused by Venturia inaequalis fungus. Spreads through ascospores released during spring rains. Cool, wet weather during bud break is critical infection period.',
        'organic_treatment': 'Copper-based or Sulfur fungicide',
        'organic_dosage': 'Sulfur: 3–5 g/L | Copper: 3 g/L',
        'organic_instructions': 'Apply from green tip to petal fall stage. Spray every 7 days or after rain. Rake and destroy fallen infected leaves.',
        'chemical_treatment': 'Captan or Myclobutanil or Difenoconazole',
        'chemical_dosage': 'As per product label',
        'chemical_instructions': 'Apply at bud-break and continue through primary scab season (green tip to petal fall). Rotate fungicide groups.',
        'prevention': 'Plant resistant apple varieties. Rake and burn fallen leaves. Ensure good air circulation through pruning.',
        'farming_tips': 'The primary infection period is from green tip to 10–14 days after petal fall. Focus spray program during this period.',
    },
    {
        'disease_key': 'Apple___Black_rot',
        'crop_name': 'Apple',
        'disease_name': 'Black Rot',
        'severity': 'High',
        'is_healthy': False,
        'symptoms': 'Reddish-purple spots on leaves with brown centers (frogeye leaf spot). Fruit rot — begins as small purple spots, enlarges, and entire fruit turns black and mummified. Cankers on branches.',
        'description': 'Caused by Botryosphaeria obtusa. Infects through wounds and pruning cuts. Mummified fruits and dead branches are primary sources of infection.',
        'organic_treatment': 'Copper fungicide + pruning',
        'organic_dosage': 'Copper Oxychloride: 3 g/L',
        'organic_instructions': 'Prune and destroy all mummified fruit and dead branches. Apply copper spray at bud break. Sanitize pruning tools.',
        'chemical_treatment': 'Captan or Myclobutanil',
        'chemical_dosage': 'As per label',
        'chemical_instructions': 'Apply from green tip through summer. Focus on removing disease reservoirs (mummified fruit, dead wood).',
        'prevention': 'Remove all mummified fruit and dead branches. Prune properly and seal cuts. Ensure good air circulation.',
        'farming_tips': 'Walk the orchard after harvest and remove all mummified fruit — they are the main source of infection next season.',
    },
    {
        'disease_key': 'Apple___Cedar_apple_rust',
        'crop_name': 'Apple',
        'disease_name': 'Cedar Apple Rust',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Bright orange-yellow spots on upper leaf surface. Orange tube-like structures on leaf underside. Fruit may show orange lesions.',
        'description': 'Caused by Gymnosporangium juniperi-virginianae. Requires both apple and Eastern red cedar (or juniper) trees to complete its life cycle. Spores spread from juniper to apple in spring.',
        'organic_treatment': 'Sulfur or Copper fungicide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply from pink bud through petal fall — this is the critical infection window. Remove nearby junipers if possible.',
        'chemical_treatment': 'Myclobutanil or Trifloxystrobin',
        'chemical_dosage': 'As per label',
        'chemical_instructions': 'Apply from pink bud through 3–4 weeks after petal fall. Spray after rain events during this period.',
        'prevention': 'Plant rust-resistant apple varieties. Remove Eastern red cedars and junipers near orchard if practical.',
        'farming_tips': 'Orange jelly-like galls on junipers in spring indicate heavy spore release — spray apples immediately.',
    },
    {
        'disease_key': 'Apple___healthy',
        'crop_name': 'Apple',
        'disease_name': 'Healthy',
        'severity': 'Low',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Leaves are green and healthy.',
        'description': 'The apple tree appears healthy. Continue regular orchard management.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue preventive program.',
        'prevention': 'Regular pruning, proper spacing, and annual fungicide program during infection-prone periods.',
        'farming_tips': 'Thin fruit clusters early season for better fruit size and reduced disease load.',
    },

    # ── Corn ────────────────────────────────────────────────────────────────────
    {
        'disease_key': 'Corn_(maize)___Northern_Leaf_Blight',
        'crop_name': 'Corn (Maize)',
        'disease_name': 'Northern Leaf Blight',
        'severity': 'High',
        'is_healthy': False,
        'symptoms': 'Long, cigar-shaped grey-green to tan lesions on leaves. Lesions can reach 15–20 cm long. Severely affected plants look burnt. Lesions appear on lower leaves first.',
        'description': 'Caused by Exserohilum turcicum fungus. Spreads by airborne spores. Cool (18–27°C) and humid conditions promote disease. Can cause 30–50% yield loss if severe.',
        'organic_treatment': 'Copper-based fungicide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply at first sign of disease. Spray every 10–14 days during humid periods.',
        'chemical_treatment': 'Propiconazole or Azoxystrobin',
        'chemical_dosage': '1 mL/L water',
        'chemical_instructions': 'Apply at early tassel stage (VT) for best results. One well-timed application is usually sufficient if applied at the right growth stage.',
        'prevention': 'Plant resistant hybrids. Practice crop rotation. Incorporate crop residue into soil after harvest.',
        'farming_tips': 'The most economical disease management in corn is selecting resistant varieties. Check local extension recommendations for resistant hybrids in your area.',
    },
    {
        'disease_key': 'Corn_(maize)___Common_rust_',
        'crop_name': 'Corn (Maize)',
        'disease_name': 'Common Rust',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Circular to elongated golden-brown to brick-red pustules on both leaf surfaces. Pustules break open to release rust-colored spores. Leaves may die prematurely.',
        'description': 'Caused by Puccinia sorghi. Spreads by airborne urediospores from southern regions. Cool temperatures (16–23°C) with long dew periods favor infection.',
        'organic_treatment': 'Sulfur-based fungicide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply at first sign of rust pustules. Best applied before significant pustule formation.',
        'chemical_treatment': 'Propiconazole or Tebuconazole',
        'chemical_dosage': '1 mL/L water',
        'chemical_instructions': 'Apply when rust pustules first appear. Repeat if disease pressure continues.',
        'prevention': 'Plant rust-resistant corn hybrids. Early planting can reduce rust exposure in some regions.',
        'farming_tips': 'If upper leaves (flag leaf and ear leaf) show significant rust, a fungicide application is warranted to protect yield.',
    },
    {
        'disease_key': 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
        'crop_name': 'Corn (Maize)',
        'disease_name': 'Gray Leaf Spot (Cercospora)',
        'severity': 'High',
        'is_healthy': False,
        'symptoms': 'Rectangular, grey to tan lesions with distinct parallel edges following leaf veins. Lesions are limited by leaf veins. Severe infections cause significant leaf blighting.',
        'description': 'Caused by Cercospora zeae-maydis. Favored by warm (25–30°C), humid conditions with extended leaf wetness. Continuous corn and minimum tillage increase disease risk.',
        'organic_treatment': 'Copper-based fungicide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply preventively during humid conditions. Improve air circulation.',
        'chemical_treatment': 'Azoxystrobin + Propiconazole (Quilt Xcel) or Pyraclostrobin',
        'chemical_dosage': 'As per label (usually 1–1.5 L/ha)',
        'chemical_instructions': 'Apply at VT–R1 stage (tasseling to silking). Best results when applied before disease becomes severe.',
        'prevention': 'Plant resistant hybrids. Rotate corn with soybean. Reduce crop residue through tillage.',
        'farming_tips': 'Gray leaf spot thrives in continuous corn fields with heavy residue. Crop rotation is the most effective long-term management strategy.',
    },
    {
        'disease_key': 'Corn_(maize)___healthy',
        'crop_name': 'Corn (Maize)',
        'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Corn plant appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Use disease-resistant hybrids. Practice crop rotation. Scout regularly.',
        'farming_tips': 'Maintain adequate soil fertility (especially nitrogen) for healthy corn growth.',
    },

    # ── Grape ───────────────────────────────────────────────────────────────────
    {
        'disease_key': 'Grape___Black_rot',
        'crop_name': 'Grape',
        'disease_name': 'Black Rot',
        'severity': 'High',
        'is_healthy': False,
        'symptoms': 'Reddish-brown circular spots with dark borders on leaves. Infected fruit turns brown, shrivels, and becomes hard black mummies. Infected shoots show black cankers.',
        'description': 'Caused by Guignardia bidwellii. Spreads during warm, wet weather. Mummified berries and cane lesions are the primary overwintering sources.',
        'organic_treatment': 'Copper-based or Sulfur fungicide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply from bud break through berry development. Remove mummified berries before bud break.',
        'chemical_treatment': 'Mancozeb or Myclobutanil',
        'chemical_dosage': 'As per label',
        'chemical_instructions': 'Critical spray window: 2 weeks before bloom through 4 weeks after bloom. Apply before and after rain events.',
        'prevention': 'Remove all mummified fruit. Prune to improve air circulation. Choose resistant grape varieties.',
        'farming_tips': 'The critical infection period is from 2 weeks before bloom to 4 weeks after bloom. Protect this window carefully.',
    },
    {
        'disease_key': 'Grape___Esca_(Black_Measles)',
        'crop_name': 'Grape',
        'disease_name': 'Esca (Black Measles)',
        'severity': 'Critical',
        'is_healthy': False,
        'symptoms': 'Tiger-striped leaf pattern (interveinal yellowing between brown margins). Berries develop dark spots (black measles). Sudden vine collapse in summer (apoplexy). Internal wood shows brown streaking.',
        'description': 'A complex wood disease caused by multiple fungi (Phaeomoniella, Phaeoacremonium, Botryosphaeria). Infects through pruning wounds. Chronic vines decline over years.',
        'organic_treatment': 'No curative treatment. Focus on prevention.',
        'organic_dosage': 'N/A',
        'organic_instructions': 'Remove severely affected vines. Paint pruning wounds with Trichoderma-based product. Avoid large pruning wounds.',
        'chemical_treatment': 'Wound sealant (lime sulfur or fungicidal wound paint)',
        'chemical_dosage': 'Apply undiluted as wound sealant',
        'chemical_instructions': 'Seal all pruning wounds immediately with protective paste. Avoid pruning in wet weather.',
        'prevention': 'Seal pruning wounds. Prune during dry weather. Remove and destroy severely infected vines. Avoid water stress.',
        'farming_tips': 'This is a long-term chronic disease. Prevention through proper pruning practices is the only effective management. Replace severely affected vines.',
    },
    {
        'disease_key': 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
        'crop_name': 'Grape',
        'disease_name': 'Leaf Blight (Isariopsis)',
        'severity': 'Medium',
        'is_healthy': False,
        'symptoms': 'Irregular dark brown spots on leaves. Spots may coalesce and cause leaf yellowing and drop. Black tufts of fungal growth on leaf underside.',
        'description': 'Caused by Isariopsis clavispora (Pseudocercospora vitis). Spreads by airborne spores during warm, humid conditions.',
        'organic_treatment': 'Copper-based fungicide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply at first sign of disease. Repeat every 10–14 days. Improve air circulation by pruning.',
        'chemical_treatment': 'Mancozeb or Carbendazim',
        'chemical_dosage': '2 g/L water',
        'chemical_instructions': 'Apply preventively during humid seasons. Rotate fungicide classes.',
        'prevention': 'Ensure good air circulation. Remove infected leaves. Avoid overhead irrigation.',
        'farming_tips': 'Prune canopy to allow good air circulation and light penetration.',
    },
    {
        'disease_key': 'Grape___healthy',
        'crop_name': 'Grape',
        'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Grape vine appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue preventive program.',
        'prevention': 'Prune properly, maintain nutrition, and follow a regular fungicide schedule during critical growth stages.',
        'farming_tips': 'Maintain detailed vineyard records including spray dates, weather, and disease observations.',
    },

    # ── Other crops (abbreviated) ────────────────────────────────────────────────
    {
        'disease_key': 'Orange___Haunglongbing_(Citrus_greening)',
        'crop_name': 'Orange',
        'disease_name': 'Huanglongbing (Citrus Greening)',
        'severity': 'Critical', 'is_healthy': False,
        'symptoms': 'Yellow mottled leaves (asymmetric blotchy mottle). Small, lopsided fruit. Bitter, sour fruit. Twig dieback. Trees decline over years.',
        'description': 'Caused by Candidatus Liberibacter bacteria, spread by Asian citrus psyllid insects. There is no cure — the disease kills the tree within years. Focus on vector control and removing infected trees.',
        'organic_treatment': 'No cure. Control psyllid with kaolin clay or reflective mulch.',
        'organic_dosage': 'N/A',
        'organic_instructions': 'Remove and destroy infected trees. Control psyllid insect vector with approved insecticides. Plant only certified disease-free nursery stock.',
        'chemical_treatment': 'Imidacloprid (for psyllid control)',
        'chemical_dosage': '1 mL/L water',
        'chemical_instructions': 'Treat for psyllid vector, not the disease itself. Apply during flush growth when psyllids attack.',
        'prevention': 'Use certified psyllid-free nursery stock. Scout regularly for psyllids. Remove and destroy infected trees immediately.',
        'farming_tips': 'Report suspected HLB to your local agricultural department immediately. This is a quarantine disease in many countries.',
    },
    {
        'disease_key': 'Peach___Bacterial_spot',
        'crop_name': 'Peach',
        'disease_name': 'Bacterial Spot',
        'severity': 'Medium', 'is_healthy': False,
        'symptoms': 'Small, water-soaked spots on leaves that turn dark purple-brown with yellow halos. Leaves drop. Fruit shows small, dark, sunken spots.',
        'description': 'Caused by Xanthomonas arboricola pv. pruni. Spreads during warm, wet weather through rain splash.',
        'organic_treatment': 'Copper bactericide',
        'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply from shuck split through harvest, especially after rain. Do not apply in hot weather (leaf burn risk).',
        'chemical_treatment': 'Oxytetracycline (if permitted) or Copper',
        'chemical_dosage': 'As per label',
        'chemical_instructions': 'Apply weekly during wet weather. Oxytetracycline use is regulated — check local guidelines.',
        'prevention': 'Plant resistant varieties. Avoid overhead irrigation. Ensure good air circulation.',
        'farming_tips': 'Select resistant peach varieties — this is the most practical management approach for bacterial spot.',
    },
    {
        'disease_key': 'Peach___healthy', 'crop_name': 'Peach', 'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Peach tree appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Annual dormant copper spray, proper pruning, and thinning fruit clusters.',
        'farming_tips': 'Thin fruit 2–3 weeks after bloom for better fruit size and reduced disease.',
    },
    {
        'disease_key': 'Pepper,_bell___Bacterial_spot', 'crop_name': 'Bell Pepper', 'disease_name': 'Bacterial Spot',
        'severity': 'Medium', 'is_healthy': False,
        'symptoms': 'Small, water-soaked spots on leaves that turn brown with yellow halos. Fruit shows raised, rough lesions.',
        'description': 'Caused by Xanthomonas bacteria. Spreads during warm, rainy weather.',
        'organic_treatment': 'Copper bactericide', 'organic_dosage': '3 g/L water',
        'organic_instructions': 'Apply preventively during wet weather. Avoid overhead irrigation.',
        'chemical_treatment': 'Copper + Mancozeb', 'chemical_dosage': '2–3 g/L water',
        'chemical_instructions': 'Apply every 7 days during humid conditions.',
        'prevention': 'Use disease-free seeds. Rotate crops. Avoid working in wet conditions.',
        'farming_tips': 'Plant certified seed or treated transplants. Use drip irrigation instead of overhead.',
    },
    {
        'disease_key': 'Pepper,_bell___healthy', 'crop_name': 'Bell Pepper', 'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Bell pepper plant appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Crop rotation, proper spacing, and adequate fertilization.',
        'farming_tips': 'Maintain consistent soil moisture for best fruit set and quality.',
    },
    {
        'disease_key': 'Strawberry___Leaf_scorch', 'crop_name': 'Strawberry', 'disease_name': 'Leaf Scorch',
        'severity': 'Medium', 'is_healthy': False,
        'symptoms': 'Small, irregular purple spots on upper leaf surface. Centers turn tan or brown. Severely affected leaves look scorched.',
        'description': 'Caused by Diplocarpon earliana fungus. Spreads during warm, wet conditions.',
        'organic_treatment': 'Copper fungicide', 'organic_dosage': '3 g/L water',
        'organic_instructions': 'Spray at first sign of disease. Remove and destroy infected leaves.',
        'chemical_treatment': 'Captan or Myclobutanil', 'chemical_dosage': 'As per label',
        'chemical_instructions': 'Apply from early spring through harvest.',
        'prevention': 'Remove old plant debris. Use disease-resistant varieties. Avoid overhead irrigation.',
        'farming_tips': 'Remove old leaves from strawberry beds in early spring to reduce disease inoculum.',
    },
    {
        'disease_key': 'Strawberry___healthy', 'crop_name': 'Strawberry', 'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Strawberry plant appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Use certified runners. Practice rotation. Renovate beds after harvest.',
        'farming_tips': 'Renovate strawberry beds after harvest by mowing and thinning to improve air circulation.',
    },
    {
        'disease_key': 'Squash___Powdery_mildew', 'crop_name': 'Squash', 'disease_name': 'Powdery Mildew',
        'severity': 'Medium', 'is_healthy': False,
        'symptoms': 'White, powdery fungal coating on upper leaf surfaces. Leaves turn yellow and dry. Severe infections spread to stems.',
        'description': 'Caused by Podosphaera xanthii or Erysiphe cichoracearum. Unlike most fungi, spreads in warm, dry conditions with low humidity.',
        'organic_treatment': 'Potassium bicarbonate or Neem oil', 'organic_dosage': 'Potassium bicarbonate: 5 g/L | Neem oil: 5 mL/L',
        'organic_instructions': 'Spray both sides of leaves. Apply every 7 days. Milk spray (1 part milk : 9 parts water) is also effective organically.',
        'chemical_treatment': 'Myclobutanil or Sulfur fungicide', 'chemical_dosage': 'As per label',
        'chemical_instructions': 'Apply at first sign of disease. Do not apply sulfur when temperature exceeds 32°C.',
        'prevention': 'Plant resistant varieties. Avoid excess nitrogen. Ensure good air circulation.',
        'farming_tips': 'Powdery mildew thrives in dry conditions — maintain adequate soil moisture and avoid drought stress.',
    },
    # Blueberry, Raspberry, Soybean (all healthy)
    {
        'disease_key': 'Blueberry___healthy', 'crop_name': 'Blueberry', 'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Blueberry plant appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Maintain acidic soil pH (4.5–5.5). Prune regularly. Scout for pests and diseases.',
        'farming_tips': 'Blueberries need acidic soil. Test soil pH annually and amend with sulfur if needed.',
    },
    {
        'disease_key': 'Cherry_(including_sour)___Powdery_mildew', 'crop_name': 'Cherry', 'disease_name': 'Powdery Mildew',
        'severity': 'Medium', 'is_healthy': False,
        'symptoms': 'White powdery coating on young leaves and shoots. Leaves curl, become distorted, and drop.',
        'description': 'Caused by Podosphaera clandestina. Favors warm, dry conditions.',
        'organic_treatment': 'Sulfur or Potassium bicarbonate', 'organic_dosage': '3–5 g/L water',
        'organic_instructions': 'Apply from bud break. Spray every 7–14 days.',
        'chemical_treatment': 'Myclobutanil', 'chemical_dosage': 'As per label',
        'chemical_instructions': 'Apply during early infection period. Observe pre-harvest intervals.',
        'prevention': 'Prune for good air circulation. Avoid excess nitrogen fertilizer.',
        'farming_tips': 'Young succulent shoots are most susceptible. Apply sprays when shoots are actively growing.',
    },
    {
        'disease_key': 'Cherry_(including_sour)___healthy', 'crop_name': 'Cherry', 'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Cherry tree appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Annual dormant copper spray. Proper pruning. Bird netting for fruit protection.',
        'farming_tips': 'Cherry trees are susceptible to bacterial canker. Avoid pruning in autumn when disease risk is highest.',
    },
    {
        'disease_key': 'Raspberry___healthy', 'crop_name': 'Raspberry', 'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Raspberry plant appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Remove old canes after harvest. Keep rows narrow for air circulation.',
        'farming_tips': 'Remove old fruited canes at ground level after harvest to reduce disease and improve air circulation.',
    },
    {
        'disease_key': 'Soybean___healthy', 'crop_name': 'Soybean', 'disease_name': 'Healthy',
        'severity': 'Low', 'is_healthy': True,
        'symptoms': 'No disease symptoms.', 'description': 'Soybean plant appears healthy.',
        'organic_treatment': 'No treatment needed', 'organic_dosage': 'N/A', 'organic_instructions': 'Continue regular care.',
        'chemical_treatment': 'No treatment needed', 'chemical_dosage': 'N/A', 'chemical_instructions': 'Continue monitoring.',
        'prevention': 'Use certified seeds with seed treatments. Rotate with corn. Scout regularly for soybean cyst nematode.',
        'farming_tips': 'Scouting at R3 (beginning pod) stage is critical for disease management decisions.',
    },
]


class Command(BaseCommand):
    help = 'Seed the DiseaseInfo table with data for all major PlantVillage disease classes'

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for data in DISEASE_DATA:
            obj, created = DiseaseInfo.objects.update_or_create(
                disease_key=data['disease_key'],
                defaults=data,
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Done! Created: {created_count}, Updated: {updated_count} disease records.'
            )
        )
